# This is a basic workflow to help you get started with Actions


name: CI-master

# Controls when the action will run.
on:
  # Triggers the workflow on push events on the develop branch

  push:
    tags:
      - '*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: tar -cvf NIDAS.tar .shrc --exclude-from=tar-exclude.txt *
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: get_branch_name
      - uses: meeDamian/github-release@v2.0.3
        with:
          token: ${{ secrets.RELEASE_SECRET }}
          tag: ${{ steps.get_tag_name.outputs.VERSION }}
          prerelease: false
          gzip: false
          files: NIDAS.tar
          allow_override: true
          body: This release was auto generated by a push on ${{ steps.get_branch_name.outputs.branch }}. Things here WILL be broken.
